import type { Metadata } from "next";
import {Faculty_Glyphic} from 'next/font/google'
import "./globals.css";
import Rodape from "@/components/Rodape";

const faculty = Faculty_Glyphic({
  subsets: ["latin"],
  weight:["400"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${faculty.className}`}
      >   
        
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
